//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.UserCustomer_Ticket = new HashSet<UserCustomer_Ticket>();
        }
    
        public int ticketID { get; set; }
        public Nullable<int> IdFlight { get; set; }
        public Nullable<int> IdType { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> priceSale { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> luggage { get; set; }
        public Nullable<int> HandLuggage { get; set; }
        public string NameTicket { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual TypeTicket TypeTicket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCustomer_Ticket> UserCustomer_Ticket { get; set; }
    }
}
