//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline21.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCustomer_Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserCustomer_Ticket()
        {
            this.invoices = new HashSet<invoice>();
        }
    
        public int IDuser_Ticket { get; set; }
        public string Name { get; set; }
        public string PhoneCustomer { get; set; }
        public string EmailCustomer { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string Nationality { get; set; }
        public string CitizenIdentificationCard { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<int> ticketID { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string IDAccount { get; set; }
        public Nullable<int> extraluggage { get; set; }
        public string securityService { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice> invoices { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
    }
}
